# Default colors
[colors.primary]
# foot background is 171717 with alpha 0.8
background = '#171717'
foreground = '#ebdbb2'

# Normal colors (Gruvbox)
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#d5c4a1'

# Bright colors (Gruvbox)
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[font]
# Match foot: JetBrainsMono Nerd Font:size=10.6
size = 10.6
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[window]
dynamic_padding = true
opacity = 0.80
blur = true
padding = { x = 4, y = 4 }

[scrolling]
history = 10000
multiplier = 3

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true
thickness = 0.15

[colors.cursor]
cursor = "#d9e5f1"
text = "#0d1925"

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\\t"
save_to_clipboard = true

[env]
TERM = "xterm-256color"
