#!/bin/sh

# Load constants and helpers
source "$HOME/.config/constants.sh"

# -----------------------------------------------------------------------------
# Bar Configuration
# -----------------------------------------------------------------------------
sketchybar --bar color=0x00000000 \
                 height=39        \
                 margin=0         \
                 y_offset=0       \
                 padding_left=8   \
                 padding_right=8

# -----------------------------------------------------------------------------
# Default Settings
# -----------------------------------------------------------------------------
# All items will inherit these properties
sketchybar --default background.border_color=$COLOR_WHITE_BRIGHT_TRANSP \
                     background.border_width=2 \
                     background.height=29 \
                     background.corner_radius=9 \
                     icon.color=$COLOR_WHITE_BRIGHT_TRANSP \
                     icon.font="$FONT_ICON" \
                     icon.highlight_color=$COLOR_BACKGROUND \
                     icon.padding_left=6 \
                     icon.padding_right=2 \
                     label.color=$COLOR_WHITE_BRIGHT_TRANSP \
                     label.font="$FONT_LABEL" \
                     label.highlight_color=$COLOR_BACKGROUND \
                     label.padding_left=2 \
                     label.padding_right=6

# Bracker defaults
sketchybar --default-for bracket background.color=0x401d2021 \
                                 background.blur_radius=20

# -----------------------------------------------------------------------------
# Load Bar Items, Brackets, and Separators
# -----------------------------------------------------------------------------
# This file now controls the order of everything on the bar
source "$HOME/.config/sketchybar/bar_items.sh"


# -----------------------------------------------------------------------------
# Finalize Setup
# -----------------------------------------------------------------------------
sketchybar --hotload true
sketchybar --update

echo "sketchybar configuration loaded"
