#!/usr/bin/env sh


yabai -m rule --add app="Spotify" --ignore

source "$HOME/.config/constants.sh"

yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_zoom_persist off
yabai -m config split_ratio 0.50
yabai -m config split_type auto
yabai -m config auto_balance off

yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10

yabai -m config layout bsp

yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

yabai -m config external_bar all:34:0

# disable borders for unimportant apps
yabai -m rule --add app="^(System Settings|System Information|Activity Monitor|FaceTime|Screen Sharing|Calculator|Stickies|TinkerTool|Progressive Downloader|Transmission|Airflow|Spotify)$" manage=off

echo "yabai configuration loaded.."
