require("modules.vars")

require("modules.autostart")
require("modules.env")
require("modules.look")
require("modules.feel")
require("modules.animations")
require("modules.input")
require("modules.rules")
require("modules.keybinds")
