#!/usr/bin/sh

EXTENSIONS=("py" "rs" "go" "c" "cpp" "sh" "zsh" "yml" "ini", "conf" "css" "lua" "json" "js")

EXTENSIONS_ARGUMENTS=$(printf -- "-e %s " "${EXTENSIONS[@]}")
# Get the first command-line argument as the path; default to current directory
#
SEARCH_PATH="${1:-.}"

# List files with chosen extensions and print their contents
fd $EXTENSIONS_ARGUMENTS . "$SEARCH_PATH" | xargs -I path sh -c 'echo -e "FILE PATH: path"; cat "path"; echo -e "\n"'
