export DOTFILES_PATH="$HOME/.dotfiles"
export ZSH_CONFIG_PATH="$DOTFILES_PATH/zsh/zsh_custom"

source "${ZSH_CONFIG_PATH}/env.zsh"
source "${ZSH_CONFIG_PATH}/opts.zsh"
source "${ZSH_CONFIG_PATH}/completion.zsh"
source "${ZSH_CONFIG_PATH}/plugins.zsh"
source "${ZSH_CONFIG_PATH}/aliases.zsh"
source "${ZSH_CONFIG_PATH}/functions.zsh"
source "${ZSH_CONFIG_PATH}/theme.zsh"
source "${ZSH_CONFIG_PATH}/hooks.zsh"

# init fzf
zvm_after_init_commands+=('source <(fzf --zsh)')

# source keybindings after zvm so we don't lose them
zvm_after_init_commands+=('source "${ZSH_CONFIG_PATH}/keybindings.zsh"')

# prompt
eval "$(starship init zsh)"
