ln -s ~/.dotfiles/alacritty/ ~/.config/alacritty
ln -s ~/.dotfiles/eza/ ~/.config/eza
ln -s ~/.dotfiles/git/ ~/.config/git
ln -s ~/.dotfiles/nvim/ ~/.config/nvim
ln -s ~/.dotfiles/foot/ ~/.config/foot
ln -s ~/.dotfiles/hypr/ ~/.config/hypr
ln -s ~/.dotfiles/fuzzel/ ~/.config/fuzzel
ln -s ~/.dotfiles/mako/ ~/.config/mako
ln -s ~/.dotfiles/waybar/ ~/.config/waybar
